POST http://localhost:3000/products
Content-Type: application/json

{
    "nome": "Name example",
    "preco": "Price example",
    "estoque": "Stock example"
}
###
GET http://localhost:3000/products
//May contain an name. 

###

PUT http://localhost:3000/products/
//Need a ID

Content-Type: application/json

{
    "nome": "Name example",
    "preco": "Price example",
    "estoque": "Stock example"
}

###
DELETE http://localhost:3000/products/
//Need a ID to work